### ISSUE TITLE
2024-04-09: GitTogether Medellin Pioneras EAFIT

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/medellin#2]
| Pregunta | Descripción |
|----------|-------------|
| Nombre del Evento |  React en acción: Potenciando el desarrollo con React Query, MSW y un ESLint personalizado + Resumen 2023 |
| Fechas del Evento | 2024-04-09 |
| ¿El evento es virtual, presencial o híbrido? | Presencial |
| Tipo de Evento | Charla |
| URL del Evento en Meetup GitHub LATAM | https://www.meetup.com/githublatam/events/299635283/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link |
| Ubicación | Universidad EAFIT Medellin |
| Descripción del Evento |  Estamos emocionadas de presentar "React en acción: Potenciando el desarrollo con React Query, MSW y un ESLint personalizado", una charla imperdible que explorará cómo estas poderosas herramientas pueden llevar tus habilidades de desarrollo al siguiente nivel. ​En esta charla, exploraremos cómo optimizar el desarrollo de aplicaciones React mediante el uso de herramientas modernas y prácticas. Descubriremos cómo mejorar la gestión de datos con React Query, simplificar las pruebas con Mock Service Worker (MSW) y mantener la calidad del código utilizando reglas personalizadas de ESLint. Además, aprenderemos técnicas efectivas para estructurar proyectos en React, lo que nos permitirá construir aplicaciones más escalables y mantenibles. Además de esta emocionante charla, también tendremos un momento especial de recapitulación y celebración de todos los eventos y logros alcanzados por nuestra comunidad en el año 2023. ¡Es una oportunidad para reflexionar sobre nuestros éxitos y mirar hacia adelante con entusiasmo hacia lo que está por venir! |
| Número esperado de participantes | 50 |
| Patrocinio |  Estimado refrigerio |
| Personal para interactuar con los asistentes | 4 |
| Swag | |

**Comment by elizarangelm** [comment]
> Pregunta	Descripción
> Nombre del Evento	React en acción: Potenciando el desarrollo con React Query, MSW y un ESLint personalizado + Resumen 2023
> Fechas del Evento	9 de marzo, 2024
> ¿El evento es virtual, presencial o híbrido?	Presencial
> Tipo de Evento	Charla
> URL del Evento en Meetup GitHub LATAM	
> Ubicación	Universidad EAFIT Medellin
> Descripción del Evento	 Estamos emocionadas de presentar "React en acción: Potenciando el desarrollo con React Query, MSW y un ESLint personalizado", una charla imperdible que explorará cómo estas poderosas herramientas pueden llevar tus habilidades de desarrollo al siguiente nivel.

​En esta charla, exploraremos cómo optimizar el desarrollo de aplicaciones React mediante el uso de herramientas modernas y prácticas. Descubriremos cómo mejorar la gestión de datos con React Query, simplificar las pruebas con Mock Service Worker (MSW) y mantener la calidad del código utilizando reglas personalizadas de ESLint. Además, aprenderemos técnicas efectivas para estructurar proyectos en React, lo que nos permitirá construir aplicaciones más escalables y mantenibles.

​Además de esta emocionante charla, también tendremos un momento especial de recapitulación y celebración de todos los eventos y logros alcanzados por nuestra comunidad en el año 2023. ¡Es una oportunidad para reflexionar sobre nuestros éxitos y mirar hacia adelante con entusiasmo hacia lo que está por venir!
> Número esperado de participantes	50
> Patrocinio	Estimado refrigerio
> Personal para interactuar con los asistentes	4
> Swag
